# Generated by Django 2.1.2 on 2019-07-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongc', '0002_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisitionname', models.CharField(max_length=200)),
                ('acquisitionnumber', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=20)),
                ('phoneno', models.CharField(max_length=20)),
            ],
        ),
    ]
