# Generated by Django 2.1.2 on 2019-07-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongc', '0004_auto_20190721_0622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media_add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medianame', models.CharField(max_length=200)),
                ('medianumber', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=20)),
                ('phoneno', models.CharField(max_length=20)),
            ],
        ),
    ]
